addSbtPlugin("com.dwijnand"      % "sbt-dynver"   % "3.3.0")
addSbtPlugin("com.dwijnand"      % "sbt-travisci" % "1.1.3")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.0.5")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.1.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.7")